version: "3.9"
services:
  app-front:
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - front:/usr/src/app/acebook/front
    depends_on:
      app-api:
        condition: service_healthy
    links: 
      - app-api
   
  app-api:
    build: ./api
    ports:
      - "4000:4000"
    volumes:
      - api:/usr/src/app/acebook/api
    healthcheck:
        test: ["CMD", "curl", "-f", "http://192.168.254.107:4000"]
        interval: 30s
        timeout: 10s
        retries: 5

volumes:
  api:
  front:

    
