version: "3"
services:
  app-api:
    build: ./api
    ports:
      - "4000:4000"
    volumes:
      - api:/usr/src/app/acebook/api
    
    

  app-front:
    build: ./front
    command:  sh -c '/usr/src/app/acebook/front/wait-for http://192.168.254.107:4000 -- echo "The api is up! Lets use it"'
    ports:
      - "3000:3000"
    volumes:
      - front:/usr/src/app/acebook/front  
    depends_on:
      - app-api
      
volumes:
  api:
  front:

    
