version: "3.9"
services:
  app-api:
    build: ./api
    ports:
      - "4000:4000"
    volumes:
      - api:/usr/src/app/acebook/api
    command: sh -c './wait-for 192.168.254.107:4000 -- docker-compose up app-front -d'
   
    
  app-front:
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - front:/usr/src/app/acebook/front
    profiles: [frontend]
    depends_on:
      - app-api  
      
volumes:
  api:
  front:

    
