version: "3"
services:
  app-front:
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - front:/usr/src/app/acebook/front
    depends_on:
      - "app-api"
      
  app-api:
    build: ./api
    ports:
      - "4000:4000"
    volumes:
      - api:/usr/src/app/acebook/api
  
  
      
volumes:
  api:
  front:

    
