version: "3.9"
services:
  app-api:
    build: ./api
    ports:
      - "4000:4000"
    volumes:
      - api:/usr/src/app/acebook/api
    
  app-front:
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - front:/usr/src/app/acebook/front
    command: ["./wait-for.sh", "192.168.254.107:4000", "--", ""]
    depends_on:
      - app-api  
      
volumes:
  api:
  front:

    
