version: "2"
services:
  app-api:
    build: ./api
    ports:
      - "4000:4000"
    volumes:
      - api:/usr/src/app/acebook/api
      
  app-front:
    depends_on:
      - app-api
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - front:/usr/src/app/acebook/front
    
      
volumes:
  api:
  front:

    
